version: '3'
services:
    drawio-renderer:
        build:
            context: .
            dockerfile: Dockerfile
        image: tomkludy/drawio-renderer:latest
        container_name: drawio-renderer
        ports:
            - "5000:5000"
